// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oepfwjtxvskkynhzxzhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lcGZ3anR4dnNra3luaHp4emh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MzUwMzMsImV4cCI6MjA2MzExMTAzM30.mV6dUpJNzhlcPTo3Lpcz0FDAwt0kYtLXmh4S5zOVX5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});